# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-02 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PPDA', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='documentUpload',
            new_name='dataUpload',
        ),
    ]
