# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-02 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PPDA', '0002_auto_20180102_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupload',
            name='epsilon',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
